package com.example.typhoon.navigate

const val ROUTE_HOME="home"
const val ROUTE_LOGIN="login"
const val ROUTE_ABOUT="about"
const val ROUTE_CONTACT="Contact"
const val ROUTE_REGISTER="register"
const val ROUTE_PERSON="person"
const val ROUTE_ADD_PRODUCT="AddProduct"
const val ROUTE_UPDATE_PRODUCT="UpdateProduct"
const val ROUTE_VIEW_PRODUCT="ViewProduct"
const val ROUTE_VIEW_UPLOAD="ViewUpload"
const val ROUTE_BUYER="Buyer"
const val ROUTE_SELLER="Seller"
const val ROUTE_DELETE_PRODUCT="DeleteProduct"
const val ROUTE_PURCHASE_PRODUCT="PurchaseProduct"
const val ROUTE_PURCHASE_CONFIRMATION="PurchaseConfirmation"
const val ROUTE_PAYMENT_METHODS="PaymentMethodsScreen"
const val ROUTE_MPESA_AUTHENTICATION="MPesaAuthenticationScreen"
const val ROUTE_PAY="Pay"

const val ROUTE_UPLOAD_PRODUCT="UploadProduct"
const val ROUTE_VIEW_PURCHASES="ViewPurchases"